# Generated by Django 5.1 on 2024-08-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_cliente_id_alter_detallefactura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
