# Generated by Django 5.1 on 2024-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_cliente_nacimiento_alter_proveedor_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.IntegerField(default=0),
        ),
    ]
